### ISSUE TITLE
OSError: dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by gabrieledcjr** [pemami4911/deep-rl#1]
getting this error when running the code

**Comment by pemami4911** [comment]
Generally, this seems to occur when you are importing python modules that dynamically load in libraries at run time. The native libraries that the gym monitor loads in to help create a display for visualization could potentially trigger this error. When multiple libraries are dynamically loaded for a single program, some kind of circular dependency bug will occasionally happen that causes the static TLS error - here's a detailed explanation https://gcc.gnu.org/ml/gcc/2015-02/msg00097.html. It probably also has to do with what specific platform you're running on, etc. 

I've never experienced this error while running this code, but I would suggest changing the order of imports as you run it (this seemed to fix this problem when I saw it occur elsewhere)  and making sure you're only importing python modules that you **really** need.

**Comment by gabrieledcjr** [comment]
I'm running this in Ubuntu 14.04 without GPU. I haven't changed anything in your code so I am just trying to run your code itself. I did try rearranging the import but I still get an error. The code only works if I set RENDER_ENV= False.

**Comment by pemami4911** [comment]
Then it sounds like the error occurs when OpenAI gym’s pyglet dependency is loading the native libraries it uses for graphics rendering. I am not sure what exactly is going on at that level that causes this problem, sorry. Not really anything I can do to help

**Comment by pemami4911** [comment]
Then it sounds like the error occurs when OpenAI gym’s pyglet dependency is loading the native libraries it uses for graphics rendering. I am not sure what exactly is going on at that level that causes this problem, sorry. Not really anything I can do to help
