### ISSUE TITLE
Divide actor gradients by batch size?

### ISSUE THREAD

**Issue by andrewLevy** [pemami4911/deep-rl#13]
Hello, 

Shouldn't the actor gradients take into account that the final gradient will be an average of a batch?  As a result, shouldn't the actor gradients be divided by the batch size?  I believe tf.gradients just adds all of the partial derivatives for all the individual data points and does not take the mean.

Thanks for creating this tutorial!

**Comment by pemami4911** [comment]
See the discussion from Issue #3

**Comment by andrewLevy** [comment]
Thanks for the quick reply!  I am a bit confused by the thread, but the conclusion is that there is some averaging occurring so no need to divide by batch size?
