### ISSUE TITLE
Possible regression to do with batch normalization

### ISSUE THREAD

**Issue by JanMatas** [pemami4911/deep-rl#18]
Hi, 

I just tried your code for the first time and I was disappointed to see that even after 500+ episodes, the rewards for Pendulum env were still in <-1000 area. I poked around a little and after reverting the latest commit (f2425330b1b7c6fb264b0a6429d4e43c3b93a417) the algorithm works as expected and achieves good results after around 100 episodes. It seems like the commit above was a regression.

**Comment by pemami4911** [comment]
Oops thanks. I commented it out by default, the master branch has been updated.
