### ISSUE TITLE
UPGRADE: Compatibility with latest version of Tensorflow (0.12.0-rc1)

### ISSUE THREAD

**Issue by pemami4911** [pemami4911/deep-rl#4]
The Tensorboard API has changed in the latest Tensorflow update, so need to make some changes to support the latest version

**Comment by afcruzs** [comment]
Hey, I just came across your blog post, I downloaded the code and it failed with the last version of tensorflow and openai. I modified the code so it runs fine with tf 1.0 and use wrappers in openai!

**Comment by pemami4911** [comment]
Awesome! Feel free to submit a pull request with the changes you made

**Comment by pemami4911** [comment]
Resolved in #7
