### ISSUE TITLE
Some questions!

### ISSUE THREAD

**Issue by allenanie** [pemami4911/deep-rl#5]
Hi! I enjoy reading your blog post a lot! Thank you!!

1. `self.actor_gradients = tf.gradients(self.scaled_out, self.network_params, -self.action_gradient)`
is "self.action_gradient" getting multiplied with the original gradients of actor?
(TF's documentation on this is hard to read)

2. I notice that DDPG's update for the actor is multiplying on the gradient of critic w.r.t. policy's chosen actions. I've seen some other AC implementations where instead of multiplying on critic's gradient, they directly multiply policy's gradients on critic's output for policy's chosen actions.

Do you think multiplying on critic's gradient is unique to DDPG (since DDPG uses action sampling), or these other implementations are potentially wrong?

**Comment by pemami4911** [comment]
To answer your questions, 

(1) Yes, that is what is happening.

You can see from the documentation that `-self.action_gradient` is the argument `grad_ys`. If I understand this correctly, in Tensorflow each Tensor has a list of gradients. `-self.action_gradient` essentially gets copied into 'self.scaled_out''s gradient list (normally, when no argument for `grad_ys` is provided, Tensorflow copies a Tensor of 1's into this list). Then, when `d(self.scaled_out)/d(self.network_params)` is computed, the gradient is "weighted" by `-self.action_gradient`, which gives the desired result.

In some ways, it's a weird abuse of Tensorflow's gradients function, but it works in this case to create a clean solution for the actor gradients 

(2) So If I understand this question correctly, I think you're talking about the gradient of the actor in a REINFORCE setting, where the actor is a stochastic policy. That's the standard algorithm for actor critic networks and the more general case of a stochastic policy. For DDPG, the Deterministic Policy Gradient Theorem allows for the use of the **deterministic** policy gradient, which has the form explained in my blog post.

**Comment by cxfneo** [comment]
nice kind of you.  I see.
